### PR TITLE
Created checkImage() method for every Industry

### PR DESCRIPTION
**Pull request by 349928465**

### CODE REVIEW

**Comment by Adrian400811** [comment]
Put checkImage() method to superclass instead.
Also TourismAndRecreation L1 and L3 are flipped.
Commit to the industries branch and keep this pr. The pr will automatically update when you push to industries branch.

**Review by Adrian400811 — CHANGES_REQUESTED** [review]
Move checkImage() method to superclass.
Rename flipped icon

**Comment by Adrian400811** [comment]
Icons fixed

**Comment by 349928465** [comment]
Closing pull request and reopening new one because my greenfoot bugged out and deleted some stuff

**Pull request closed without merging**
